### ISSUE TITLE
代码写的真漂亮，代码架构真优秀

### ISSUE THREAD

**Issue by xiyuan-code** [cty123/TrojanRust#4]
在尝试把reqwest 与此进行结合，通过阅读理解其实现过程，发现代码写的如此简洁、架构设计的如此清晰，让我理解起来很顺畅，这代码很适合我这种新手（10年前后端开发经验）学习rust和网络编程，膜拜大神～

**Comment by cty123** [comment]
其实还有不少优化空间，欢迎提pr/issue
